packages:
  - 'packages/api'
  - 'packages/web'
  - 'packages/shared'
  - 'packages/mobile'
  - 'packages/design-system/web'
  - 'packages/design-system/mobile'
  - 'packages/design-system/tokens'
  - 'tools/*'
