name: alkitu_mobile
description: Alkitu Mobile Application - Cross-platform mobile app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Network & API
  dio: ^5.3.2
  graphql_flutter: ^5.1.2
  connectivity_plus: ^5.0.1

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # UI & Navigation
  go_router: ^13.2.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # Utils
  intl: ^0.18.1
  logging: ^1.2.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

  # Authentication
  local_auth: ^2.1.6
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
